### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by qmj123** [takiyu/hyperface#8]
Hi @takiyu 
I have a problem that must the Test part  use gpu?
Thank you very much!

**Comment by takiyu** [comment]
To test the model, GPU is not always needed.
Now I downloaded the code and the pretrained model, and it was able to run a simple test with the following command on my laptop PC.
```
python ./scripts/use_on_file.py --model model_epoch_190 --img sample_images/lena_face.png
```

**Comment by qmj123** [comment]
Hi 
Thank you for your reply!
I already downloaded and use 'python ./scripts/use_on_file.py --model model_epoch_190 --img sample_images/lena_face.png' to test,but  it has a problem：

qwe@qwe:~/downloads/hyperface-master$ python ./scripts/use_on_file.py --model model_epoch_190 --img sample_images/lena_face.png
[2018/01/12 21:20:18] INFO (26588) __main__ : HyperFace Evaluation
[2018/01/12 21:20:18] INFO (26588) config : Load config from "config.json"
[2018/01/12 21:20:18] INFO (26588) __main__ : Define a HyperFace model
[2018/01/12 21:20:21] INFO (26588) __main__ : Initialize a model using model "model_epoch_190"
Traceback (most recent call last):
  File "./scripts/use_on_file.py", line 57, in <module>
    chainer.serializers.load_npz(args.model, model)
  File "/usr/local/lib/python2.7/dist-packages/chainer/serializers/npz.py", line 119, in load_npz
    with numpy.load(filename) as f:
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 21] Is a directory: 'model_epoch_190'
Can you help me ?
Thanks!

**Comment by takiyu** [comment]
It seems loading the model file is failed.
I think you unziped the model file `model_epoch_190`. Do not unzip it.
If you downloaded from Google Drive, it is automatically opened with `zip explorer`, so be careful.

**Comment by qmj123** [comment]
OK! I try again!
Thank you!
