### ISSUE TITLE
ValueError: Invalid async_mode specified

### ISSUE THREAD

**Issue by Mohammadamin-Barekatain** [takiyu/hyperface#9]
I get an error when I run:

> python ./scripts/demo_live.py --model model_epoch_190

I have a MacOsX system and Here is the log: 
```
Traceback (most recent call last):
  File "/anaconda/envs/hyperface/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda/envs/hyperface/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/aminbarekatain/Desktop/hyperface/scripts/extensions/imgliveuploader/app.py", line 99, in new_server
    logger=False, engineio_logger=False)
  File "/anaconda/envs/hyperface/lib/python2.7/site-packages/flask_socketio/__init__.py", line 119, in __init__
    self.init_app(app, **kwargs)
  File "/anaconda/envs/hyperface/lib/python2.7/site-packages/flask_socketio/__init__.py", line 144, in init_app
    self.server = socketio.Server(**self.server_options)
  File "/anaconda/envs/hyperface/lib/python2.7/site-packages/socketio/server.py", line 89, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
  File "/anaconda/envs/hyperface/lib/python2.7/site-packages/engineio/server.py", line 122, in __init__
    raise ValueError('Invalid async_mode specified')

```

Can you help me to fix this problem?

**Comment by takiyu** [comment]
Have you installed `eventlet`? It is used for asynchronous networking process in `flask-socketio`.

**Comment by Mohammadamin-Barekatain** [comment]
Thank you for your fast response. That solved my problem and it's working now
